zecca_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../../dataplatform/storage.duckdb"
      extensions:
        - parquet
        - httpfs
      settings:
        threads: 8
