{{
    config(
        materialized="table",
    )
}}


with candles as ({{ candles_enhanced("1d", [1, 5, 14, 20, 30, 62, 126, 252]) }})

select
    timeframe,
    extract(year from timeframe) as year,
    extract(month from timeframe) as month,
    symbol,
    open,
    close,
    high,
    low,
    volume,
    log_return_1_steps as log_return_1d,
    log_return_5_steps as log_return_1w,
    log_return_20_steps as log_return_1m,
    log_return_30_steps,
    log_return_62_steps as log_return_1q,
    log_return_126_steps as log_return_6m,
    log_return_252_steps as log_return_1y,
    return_1_steps as return_1d,
    return_5_steps as return_1w,
    return_20_steps as return_1m,
    return_30_steps,
    return_62_steps as return_1q,
    return_126_steps as return_6m,
    return_252_steps as return_1y,
    open_rolling_1_steps as open_rolling_1_steps_1d,
    open_rolling_5_steps as open_rolling_1w,
    open_rolling_20_steps as open_rolling_1m,
    open_rolling_30_steps,
    open_rolling_62_steps as open_rolling_1q,
    open_rolling_126_steps as open_rolling_6m,
    open_rolling_252_steps as open_rolling_1y,
    volatility_1_steps as volatility_1_steps_1d,
    volatility_5_steps as volatility_1w,
    volatility_20_steps as volatility_1m,
    volatility_30_steps,
    volatility_62_steps as volatility_1q,
    volatility_126_steps as volatility_6m,
    volatility_252_steps as volatility_1y,
    sharpe_1_steps as sharpe_1_steps_1d,
    sharpe_5_steps as sharpe_1w,
    sharpe_20_steps as sharpe_1m,
    sharpe_30_steps,
    sharpe_62_steps as sharpe_1q,
    sharpe_126_steps as sharpe_6m,
    sharpe_252_steps as sharpe_1y,
    rsi_14_steps as rsi,
    overbought_14_steps as overbought,
    oversold_14_steps as oversold,
    rsi_1_steps as rsi_1d,
    rsi_5_steps as rsi_1w,
    rsi_20_steps as rsi_1m,
    rsi_30_steps,
    rsi_62_steps as rsi_1q,
    rsi_126_steps as rsi_6m,
    rsi_252_steps as rsi_1y,
from candles
