ingestion_dir: dataplatform/raw
incremental: True
backup: True

# models skipped in daily processing
skip:
  - silver.sec_indicators
  - silver.visibility_graph_indicators
  - silver.fama_french_5
  - gold.sec_indicators
